# Lint:
# - INSTALL: https://github.com/rhysd/actionlint/blob/main/docs/install.md
# - USE: actionlint .github/workflows/kiwigrid-k8s-sidecar-scan-custom.yaml
name: "k8s-sidecar-img-custom"
on: workflow_dispatch
jobs:
  custom:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout k8s-sidecar Repo
        uses: actions/checkout@v3
        with:
          repository: kiwigrid/k8s-sidecar
      - name: Checkout This Repo Within k8s-sidecar
        uses: actions/checkout@v3
        with:
          path: .buildit-actions
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build Docker Image As Tar File
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./.buildit-actions/.github/k8s-sidecar-img-custom/Dockerfile
          push: false
          outputs: type=docker,dest=kiwigrid-k8s-sidecar.tar
          tags: kiwigrid-k8s-sidecar:scanning
      - name: Run Trivy Vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          input: /github/workspace/kiwigrid-k8s-sidecar.tar
          exit-code: '1'
