# Lint:
# - INSTALL: https://github.com/rhysd/actionlint/blob/main/docs/install.md
# - USE: actionlint .github/workflows/kiwigrid-k8s-sidecar-scan.yaml
name: "upstream: kiwigrid/k8s-sidecar img scan"
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Upstream
        uses: actions/checkout@v3
        with:
          repository: kiwigrid/k8s-sidecar
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: buildit/kiwigrid-k8s-sidecar:upstream
